### ISSUE TITLE
Tensor-hom adjunction functions

### ISSUE THREAD

**Issue by mroman42** [homalg-project/FinSetsForCAP#22]
Are `LambdaIntroduction` and `LambdaElimination` from [CAP documentation, section 7.4](https://www.gap-system.org/Manuals/pkg/CAP-2017.09.25/doc/chap7.html#X849F4CB58466EAEB) already implemented? I could write a pull request for them if they are not.

**Comment by zickgraf** [comment]
They are not implemented. Pull requests are welcome :-)

**Comment by zickgraf** [comment]
Actually, they should probably be derived automatically, but the necessary filters are not set. I will look into this.

**Comment by zickgraf** [comment]
In #23 the necessary filters are set, so now `LambdaIntroduction` and `LambdaElimination` are derived automatically by CAP.

**Comment by mohamed-barakat** [comment]
Thanks.

**Comment by mroman42** [comment]
Thank you! I close the issue then.
