### ISSUE TITLE
Use SkeletalFinSets as a workhorse

### ISSUE THREAD

**Issue by sebastianpos** [homalg-project/FinSetsForCAP#30]
I would like to use `SkeletalFinSets` as the range of a homomorphism structure of categories that only have finitely many morphisms between two objects (like finite groups or monoids as categories, or acyclic quivers as categories). For this, some constructions of `SkeletalFinSets` need to be as fast as possible (in particular the morphism constructor).

Is it possible to provide a constructor for `SkeletalFinSets` for the user, so that it is possible to pipe options to the constructor like the one introduced in #405 that immediately give a vast speed-up
in my use case?

**Comment by sebastianpos** [comment]
The constructor `FinSet` could have the signature `category, integer` and be declared as a `KeyDependentOperation` (in order to use GAP's caching). I do it that way for the category of rows.
The single argument version of `FinSet` could then call the 2-argument version with the hardcoded global variable.

`MapOfFinSets` can extract the category from the source or range argument.

**Comment by zickgraf** [comment]
Sounds perfect :-) Would you like to submit a PR?

Another note: when working with homomorphism structures I guess you want to compute lifts in `SkeletalFinSets`. As far as I know these are currently not implemented :-(

**Comment by sebastianpos** [comment]
Yes, I will work on a PR.

Actually, I will use a functor `SkeletalFinSets -> Rows(R)` to lift these "finitary categories" to an R-linear level. And once there, I can happily compute my lifts :-)

**Comment by mohamed-barakat** [comment]
> I would like to use `SkeletalFinSets` as the range of a homomorphism structure of categories that only have finitely many morphisms between two objects (like finite groups or monoids as categories, or acyclic quivers as categories).

You probably mean the categories generated by the finite acyclic quivers. We do not have such a constructor `CategoryClosure` yet. The category constructor `Algebroid` (wrapping `QPA`'s path algebras) is the composition of the two missing constructors: `R-LinearClosure` o `CategoryClosure`.
