### ISSUE TITLE
Is there something missing for `SkeletalFinSets!.supports_empty_limits := true`?

### ISSUE THREAD

**Issue by mohamed-barakat** [homalg-project/FinSetsForCAP#83]

**Comment by zickgraf** [comment]
Now FinSets and SkeletalFinSets nearly support empty limits: https://github.com/homalg-project/FinSetsForCAP/blob/0f030128714c0aa468441e52ca77bb55c6a3554a/gap/SkeletalFinSetsForCAP.gi#L18-L22 I currently have no idea how to work around this without modifying CompilerForCAP or hiding parts of the code in a helper function unavailable to CompilerForCAP. The latter approach sadly leads to function call overhead which is detrimental to performance in large examples.

**Comment by mohamed-barakat** [comment]
Thank you very much. Let us discuss this during our next meeting.
