### ISSUE TITLE
whitespaces in Display output

### ISSUE THREAD

**Issue by zickgraf** [homalg-project/FinSetsForCAP#9]
d4c354d6190d9527eda2fbd63bc543a2b8d0fff0 removes some whitespace in an example file. However, GAP actually produces this whitespace in the output (I assume because it regards lists of lists as matrices). We could avoid this by using `Print( AsList( S ), "\n" );` instead of `Display( AsList( S ) );` in our Display method for finite sets. Would this be a reasonable change?

**Comment by mohamed-barakat** [comment]
If these white spaces are automatically generated then I am happy with them. I just thought they are copy paste mistakes. If not my commit should be reverted.

**Comment by zickgraf** [comment]
I am not too happy with the white spaces (and the new lines) because they only appear for integers:
```
gap> M := FinSet( [ [ 1 ], [ 2 ] ] );;
gap> N := FinSet( [ [ "1" ], [ "2" ] ] );;
gap> Display( M );
[ [  1 ],
  [  2 ] ]
gap> Display( N );
[ [ "1" ], [ "2" ] ]
```
In my opinion, the format of the output should not depend on the data types of the elements in the finite set. Using `Print` gives a consistent result:
```
gap> Print( AsList( M ), "\n" );
[ [ 1 ], [ 2 ] ]
gap> Print( AsList( N ), "\n" );
[ [ "1" ], [ "2" ] ]
```

**Comment by mohamed-barakat** [comment]
I think they appear for lists L for which `IsMatrix( L ) = true`. I agree with your suggestion.
